markdown: rdiscount
auto: true

exclude: ["README.md", "LICENSE.md", "TODO.md", "build", "test"]

owner-name: your name
owner-page: your homepage
owner-email: your email

license: your license of choice

test: "test"

sass:
  sass_dir: _sass
  style: :compressed
