markdown: rdiscount
auto: true

exclude: ["README.md", "LICENSE.md", "TODO.md", "build", "test"]

name: Pageo Lavender Farm
homepage: http://pageolavenderfarm.com/
email: info@pageolavenderfarm.com
phone: 209.632.5052
fax: 209.634.1379

license: your license of choice


sass:
  sass_dir: _sass
  style: :compressed
